### ISSUE TITLE
Version 20.1.1, AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by AlexandreYang** [PyCQA/flake8-bugbear#108]
CC @Zac-HD @cooperlees 

Hey, we are getting this error after upgrade to `flake8-bugbear==20.1.1` (`20.1.0` works fine):

```
  File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 150, in visit_ExceptHandler
    names.append("{}.{}".format(e.value.id, e.attr))
AttributeError: 'Attribute' object has no attribute 'id'
```

<details><summary>Show full stacktrace</summary>
<p>

```
2020-01-05T19:55:25.4865073Z Traceback (most recent call last):
2020-01-05T19:55:25.4865330Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/multiprocessing/pool.py", line 121, in worker
2020-01-05T19:55:25.4865652Z     result = (True, func(*args, **kwds))
2020-01-05T19:55:25.4866300Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/checker.py", line 666, in _run_checks
2020-01-05T19:55:25.4866616Z     return checker.run_checks()
2020-01-05T19:55:25.4867190Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/checker.py", line 598, in run_checks
2020-01-05T19:55:25.4867536Z     self.run_ast_checks()
2020-01-05T19:55:25.4868064Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/checker.py", line 502, in run_ast_checks
2020-01-05T19:55:25.4868414Z     for (line_number, offset, text, check) in runner:
2020-01-05T19:55:25.4868944Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 34, in run
2020-01-05T19:55:25.4869587Z     visitor.visit(self.tree)
2020-01-05T19:55:25.4870122Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 135, in visit
2020-01-05T19:55:25.4870474Z     super().visit(node)
2020-01-05T19:55:25.4870764Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 271, in visit
2020-01-05T19:55:25.4871012Z     return visitor(node)
2020-01-05T19:55:25.4871300Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 279, in generic_visit
2020-01-05T19:55:25.4871543Z     self.visit(item)
2020-01-05T19:55:25.4872360Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 135, in visit
2020-01-05T19:55:25.4872950Z     super().visit(node)
2020-01-05T19:55:25.4877504Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 271, in visit
2020-01-05T19:55:25.4878104Z     return visitor(node)
2020-01-05T19:55:25.4878934Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 271, in visit_ClassDef
2020-01-05T19:55:25.4879331Z     self.generic_visit(node)
2020-01-05T19:55:25.4879809Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 279, in generic_visit
2020-01-05T19:55:25.4880331Z     self.visit(item)
2020-01-05T19:55:25.4881377Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 135, in visit
2020-01-05T19:55:25.4881709Z     super().visit(node)
2020-01-05T19:55:25.4882043Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 271, in visit
2020-01-05T19:55:25.4882366Z     return visitor(node)
2020-01-05T19:55:25.4882948Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 267, in visit_FunctionDef
2020-01-05T19:55:25.4883342Z     self.generic_visit(node)
2020-01-05T19:55:25.4883633Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 279, in generic_visit
2020-01-05T19:55:25.4883977Z     self.visit(item)
2020-01-05T19:55:25.4884933Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 135, in visit
2020-01-05T19:55:25.4885248Z     super().visit(node)
2020-01-05T19:55:25.4885698Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 271, in visit
2020-01-05T19:55:25.4885947Z     return visitor(node)
2020-01-05T19:55:25.4886510Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 275, in visit_Try
2020-01-05T19:55:25.4886861Z     self.generic_visit(node)
2020-01-05T19:55:25.4887118Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 279, in generic_visit
2020-01-05T19:55:25.4887411Z     self.visit(item)
2020-01-05T19:55:25.4887925Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 135, in visit
2020-01-05T19:55:25.4888484Z     super().visit(node)
2020-01-05T19:55:25.4888758Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/ast.py", line 271, in visit
2020-01-05T19:55:25.4889062Z     return visitor(node)
2020-01-05T19:55:25.4889660Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/bugbear.py", line 150, in visit_ExceptHandler
2020-01-05T19:55:25.4889978Z     names.append("{}.{}".format(e.value.id, e.attr))
2020-01-05T19:55:25.4890750Z AttributeError: 'Attribute' object has no attribute 'id'
2020-01-05T19:55:25.4891043Z """
2020-01-05T19:55:25.4891306Z 
2020-01-05T19:55:25.4891553Z The above exception was the direct cause of the following exception:
2020-01-05T19:55:25.4891824Z 
2020-01-05T19:55:25.4892056Z Traceback (most recent call last):
2020-01-05T19:55:25.4892362Z   File "/home/vsts/work/1/s/druid/.tox/style/bin/flake8", line 8, in <module>
2020-01-05T19:55:25.4892770Z     sys.exit(main())
2020-01-05T19:55:25.4893338Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
2020-01-05T19:55:25.4893850Z     app.run(argv)
2020-01-05T19:55:25.4894513Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
2020-01-05T19:55:25.4894897Z     self._run(argv)
2020-01-05T19:55:25.4896230Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
2020-01-05T19:55:25.4896613Z     self.run_checks()
2020-01-05T19:55:25.4897283Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/main/application.py", line 300, in run_checks
2020-01-05T19:55:25.4897588Z     self.file_checker_manager.run()
2020-01-05T19:55:25.4898100Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/checker.py", line 329, in run
2020-01-05T19:55:25.4898390Z     self.run_parallel()
2020-01-05T19:55:25.4899047Z   File "/home/vsts/work/1/s/druid/.tox/style/lib/python3.7/site-packages/flake8/checker.py", line 293, in run_parallel
2020-01-05T19:55:25.4899688Z     for ret in pool_map:
2020-01-05T19:55:25.4899922Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/multiprocessing/pool.py", line 748, in next
2020-01-05T19:55:25.4900110Z     raise value
2020-01-05T19:55:25.4900577Z AttributeError: 'Attribute' object has no attribute 'id'
2020-01-05T19:55:25.5194690Z [31mERROR: InvocationError for command /home/vsts/work/1/s/druid/.tox/style/bin/flake8 --config=../.flake8 . (exited with code 1)
```

</p>
</details>

This can be reproduced with this minimal case:

```
import requests

def foo():
    try:
        pass
    except (requests.exceptions.RequestException, AttributeError):
        pass
```

flake8 config
```
# TODO: port this to pyproject.toml when supported: https://gitlab.com/pycqa/flake8/merge_requests/245

[flake8]
select = B,C,E,F,W,B001,B003,B006,B007,B301,B305,B306,B902
# Ignore reasons:
# - G200: logging exception is ok, we don't always want to log the stack trace too
ignore = E203,E722,W503,G200
exclude = .eggs,.tox,build,compat.py,__init__.py,datadog_checks/dev/tooling/templates/*,datadog_checks/*/vendor/*
max-line-length = 120
```

When `requests.exceptions.RequestException` is changed to something else like `IndexError`, it works fine. So, somehow when using `requests.exceptions.RequestException`, the `Attribute.id` is missing.

Any idea why?

## Additional info

Concrete CI fail example: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=6209&view=logs&jobId=5e7fd8a3-b132-5246-3e9c-553f252343b6&j=6856723d-645b-5a7b-98a0-8af874afe33f&t=763e838c-8ffd-5432-4e53-c53eda38d033

**Comment by Zac-HD** [comment]
Oh darn, this will be because there's a an attribute-of-an-attribute somewhere and I only handled one layer deep 😕

I'll open a PR to fix that momentarily... and add some fuzz tests to make sure I got it right.

**Comment by peterjc** [comment]
Thank you! You had that fix out quick enough that we didn't need to do a work around pinning an earlier version for continuous integration testing.

**Comment by AlexandreYang** [comment]
@Zac-HD Kudos, for fixing the issue so quickly. Thx!
