### ISSUE TITLE
test_does_not_crash_on_any_valid_code hypothesis HealthCheck fails on 3.10.0a0

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#128]
Haven't debugged. But it raises `hypothesis.errors.FailedHealthCheck`

```
$ coverage run tests/test_bugbear.py
.....................You can add @seed(6108964495495638932952417326211249481) to this test to reproduce this failure.
E.
======================================================================
ERROR: test_does_not_crash_on_any_valid_code (__main__.TestFuzz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PyCQA/flake8-bugbear/tests/test_bugbear.py", line 281, in test_does_not_crash_on_any_valid_code
    def test_does_not_crash_on_any_valid_code(self, syntax_tree):
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/core.py", line 1141, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/core.py", line 1106, in wrapped_test
    state.run_engine()
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/core.py", line 730, in run_engine
    runner.run()
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 458, in run
    self._run()
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 857, in _run
    self.generate_new_examples()
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 661, in generate_new_examples
    minimal_example = self.cached_test_function(
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 1034, in cached_test_function
    self.test_function(data)
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 289, in test_function
    self.record_for_health_check(data)
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 368, in record_for_health_check
    fail_health_check(
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/hypothesis/internal/healthcheck.py", line 32, in fail_health_check
    raise FailedHealthCheck(message, label)
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 3 valid examples in 3.97 seconds (0 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
```

**Comment by Zac-HD** [comment]
I think this is actually just a https://github.com/Zac-HD/hypothesmith performance issue, which is not *that* surprising in early-alpha software 🤷‍♂️   Happy to have a report upstream, but tbh it's not a priority at the moment.
