### ISSUE TITLE
Fix Fuzz error in python3.9

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#207]
Seen this on multiple PRs now and I don't quite understand it.

```
Run coverage run tests/test_bugbear.py
.........................E...
======================================================================
ERROR: test_does_not_crash_on_any_valid_code (__main__.TestFuzz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 110, in draw_symbol
    compile(
SystemError: Negative size passed to PyUnicode_New

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/flake8-bugbear/flake8-bugbear/tests/test_bugbear.py", line 333, in test_does_not_crash_on_any_valid_code
    @given(from_grammar().map(ast.parse))
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesis/core.py", line 1197, in wrapped_test
    raise the_error_hypothesis_found
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 89, in do_draw
    result = super().do_draw(data)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 153, in do_draw
    self.draw_symbol(data, start, state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 181, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 181, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 181, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 129, in draw_symbol
    raise type(err)(
SystemError: compile('fromAimport*\\ \n;\n', '<string>', 'single') raised SystemError: Negative size passed to PyUnicode_New

----------------------------------------------------------------------
Ran 29 tests in 10.170s

FAILED (errors=1)
Highest target scores:
               6  (label='(hypothesmith) number of unique ast node types')
               7  (label='(hypothesmith) instructions in bytecode')
              10  (label='(hypothesmith) total number of ast nodes')


You can reproduce this example by temporarily adding @reproduce_failure('6.27.1', b'AXicY2RkYGJhZGBkgAJmRhgTQgMAAZAAEQ==') as a decorator on your test case
Error: Process completed with exit code 1.
```

Example fail: https://github.com/PyCQA/flake8-bugbear/runs/4306872686?check_suite_focus=true

**Comment by cooperlees** [comment]
Hypothesis has a workaround released until cpython bug is fixed.
