### ISSUE TITLE
"maximum recursion depth exceeded while calling a Python object" while calling long chain of methods

### ISSUE THREAD

**Issue by gladykov** [PyCQA/flake8-bugbear#295]
When multiple methods are chained on the object together (~140), Bugbear will `cause maximum recursion depth exceeded while calling a Python object`

Steps to reproduce:

0. Windows, Python 3.8, Bugbear [22.9.23](https://github.com/PyCQA/flake8-bugbear/releases/tag/22.9.23)
1. Download and rename [chain_method.txt](https://github.com/PyCQA/flake8-bugbear/files/9708330/chain_method.txt) to chain_method.py
2. 

```python -m pip install --upgrade pip
pip install flake8 flake8-bugbear
flake8 .
```

Result:

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\flake8\main\cli.py", line 22, in main
    app.run(argv)
  File "c:\program files\python38\lib\site-packages\flake8\main\application.py", line 375, in run
    self._run(argv)
  File "c:\program files\python38\lib\site-packages\flake8\main\application.py", line 364, in _run
    self.run_checks()
  File "c:\program files\python38\lib\site-packages\flake8\main\application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "c:\program files\python38\lib\site-packages\flake8\checker.py", line 311, in run
    self.run_serial()
  File "c:\program files\python38\lib\site-packages\flake8\checker.py", line 295, in run_serial
    checker.run_checks()
  File "c:\program files\python38\lib\site-packages\flake8\checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "c:\program files\python38\lib\site-packages\flake8\checker.py", line 500, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 60, in run
    visitor.visit(self.tree)
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 268, in visit
    super().visit(node)
  File "c:\program files\python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "c:\program files\python38\lib\ast.py", line 379, in generic_visit
    self.visit(item)
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 268, in visit
    super().visit(node)
  File "c:\program files\python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "c:\program files\python38\lib\ast.py", line 381, in generic_visit
    self.visit(value)
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 268, in visit
    super().visit(node)
  File "c:\program files\python38\lib\ast.py", line 371, in visit
    return visitor(node)
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 357, in visit_Call
    self.generic_visit(node)
  File "c:\program files\python38\lib\ast.py", line 381, in generic_visit
    self.visit(value)
  File "c:\program files\python38\lib\site-packages\bugbear.py", line 268, in visit
```

This continues until error is reached:  

```  
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Use case:
We use such long chains to describe internal schema of DB

**Comment by cooperlees** [comment]
So what do you actually want here to fix it? I guess we could all a config parameter to set `sys.setrecursionlimit`: https://docs.python.org/3/library/sys.html#sys.setrecursionlimit

You could then set this for your deep recursive code ...

**Comment by gladykov** [comment]
Thank you, I was not aware of this setting. Not sure then if bugbear would be the best place. Maybe flake8 repo would be a place to ask for command line parameter, to increase it - would be more efficient , as in theory would apply to any plugin (?)

**Comment by cooperlees** [comment]
Agree. I only suggested config as we (bugbear plug-in) has no way to change the CLI but I think we can get at the config easier. 

Yes, this could occur on any plug-in depending how it works. We are AST based so your large files cause a lot of recursion with our parsing. You could also, be hilighting a bug, but I don’t think so due to you claiming very large files.

It’s definitely a better solution to ask flake8 itself here how they want to handle it.

**Comment by gladykov** [comment]
Thank you. Well maybe someone will also encounter this in the future. For now we divided those long blocks of chained methods. Closing then.

**Comment by m-aciek** [comment]
I'm hitting what appears to be the same class of problem in 2026, with current versions of Flake8 and flake8-bugbear.

The visible failure still originates from bugbear's AST visitor and results in:

```text
RecursionError: maximum recursion depth exceeded
```

The traceback ends up in `bugbear.py` during AST traversal.

I realize that deeply nested ASTs may inherently run into Python recursion limits and that the underlying limitation may not be specific to flake8-bugbear. However, from a user perspective, the current experience is difficult to diagnose:

* Flake8 aborts with a traceback.
* There is little indication which file triggered the problem.
* I couldn't find documentation or troubleshooting guidance describing this failure mode.

Would maintainers consider either:

1. documenting this limitation (and possible workarounds), or
2. pointing users to the project where such behavior should be reported and handled?

I'm happy to provide versions, `flake8 --bug-report`, and more context if that would help determine whether this is expected behavior or a bug.

**Comment by m-aciek** [comment]
It looks like catching the `RecursionError` to `PluginExecutionFailed` would improve user experience: https://github.com/PyCQA/flake8/blob/bb943328eff3518ee193adbddffdfe15e239c3f7/src/flake8/exceptions.py#L55

RecursionError with bare pyflakes ends up with: 
```
sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError('maximum recursion depth exceeded')
Run flake8 with greater verbosity to see more details
```
