### ISSUE TITLE
Feature request: a rule for calling super().__init__() in custom exception's __init__()

### ISSUE THREAD

**Issue by m-aciek** [PyCQA/flake8-bugbear#421]
```python
class CustomException(Exception):
    def __init__(self, custom: int, arguments: str) -> None:
        self.msg = f"Something specific happened with custom: {int} and {arguments}"
```

Above exception class has an issue, in my personal experience it's quite common. The implementer assumes, that they will use the `self.msg` parameter during exception handling. The issue araises when the exception gets anywhere else as the its string representation is as follows:

```python
>>> raise CustomException(42, 'test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: (42, 'test')
```

and when the exception is instantiated with keyword arguments, we lose the information about the arguments' values.

```python
>>> raise CustomException(custom=1, arguments='two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException
```

How to fix it? By calling `super().__init__()` in the constructor. That way the string representation of the custom exception will contain the error message.

```python
class CustomException(Exception):
    def __init__(self, custom: int, arguments: str) -> None:
        self.msg = "Something specific happened with custom: {int} and {arguments}"
        super().__init__(self.msg)
>>> raise CustomException(1, 'two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: Something specific happened with custom: 1 and two
>>> raise CustomException(custom=1, parameters='two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: Something specific happened with custom: 1 and two
```

**Specification proposal**

If a class:
* inherits from from `Exception`,
* doesn't implement own `__str__()` method,
* its `__init__()` method doesn't enforce any positional-only argument, 
* and doesn't call `super().__init__()` in its `__init__()` method

Then:
* new rule should raise an error, calling to fix it.

**Comment by cooperlees** [comment]
Should the example be:
```python
class CustomException(Exception):
    def __init__(self, custom: int, arguments: str) -> None:
        self.msg = f"Something specific happened with custom: {custom} and {arguments}"  # <-- custom
         super().__init__(self.msg)
```

Seems a good check for me and a bug waiting to happen. Please explain why this is bad to do in the README. And as always, provide good tests with correct code and bad code please.

**Comment by m-aciek** [comment]
> Should the example be:

Yes, right, thanks. I fixed the original post.

**Comment by jakkdl** [comment]
This rule could probably also cover https://github.com/python/cpython/issues/125782
i.e. "exception class accepts arguments, but doesn't pass those to `super().__init__(..)`"

> * inherits from from `Exception`

we may want to be broader than this, as user exceptions may inherit from any built-in exception - or from other user exceptions that themselves inherit from `Exception`. This is how I encountered it in the wild
https://github.com/python-trio/trio-websocket/blob/f5fd6d77db16a7b527d670c4045fa1d53e621c35/trio_websocket/_impl.py#L587-L605

Checking inheritance from any built-in exception is fairly straightforward, checking inheritance from any user exception is trickier - one approach is saving exception classes encountered previously in the file, another is to trigger on classes that inherit from *something, and the class name or the super() class name ends with "Exception[Group]" or "Error".

Oh and same goes for `Warning` classes, in case of `-Werror`

**Comment by jenstroeger** [comment]
Interesting check, and I’d like to pick up this discussion here to understand better what exactly is going on…

Unfortunately, I wasn’t able to find a definition of the actual Exception initializer [here](https://docs.python.org/3/library/exceptions.html#Exception) or [here](https://docs.python.org/3/tutorial/errors.html) or a discussion [here](https://discuss.python.org/), so I’m not quite sure what arguments the Exception class expects. If I check the repl:

```
>>> help(Exception)
Help on class Exception in module builtins:

class Exception(BaseException)
 |  Common base class for all non-exit exceptions.
 |  ...
 |
 |  Methods defined here:
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 | ...
```

then that’s not much help either. If I look at the CPython code [here](https://github.com/python/cpython/blob/efde4333bfcdd1e24c2ab8a5b2eea071b6697a8f/Objects/exceptions.c#L80) then indeed it seems like kwargs are rejected and only args are passed along. But which ones? 

For example, suppose this class:
```python
class BaseApplicationError(Exception):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
        super().__init__()  # Am I supposed to pass all args?
```
which takes a few custom arguments — to implement some custom state and to manage application-specific args — but none of them is known to the base class Exception. So,
```python
>>> raise BaseApplicationError(1,2,3)
Traceback (most recent call last):
  File "<python-input-6>", line 1, in <module>
    raise BaseApplicationError(1,2,3)
BaseApplicationError
```
whereas passing them to `super().__init__()` results in
```python
>>> raise BaseApplicationError(1,2,3)
Traceback (most recent call last):
  File "<python-input-8>", line 1, in <module>
    raise BaseApplicationError(1,2,3)
BaseApplicationError: (1, 2, 3)
```
So this check does make sense, but can somebody please point me at some original Python docs, if any exist? Shall I, as indicated by this check and by tests, just pass _every_ arg up to the base class initializer, regardless of what it is?

**Comment by jakkdl** [comment]
I'm not aware of any original Python docs, I had to dig into the CPython source code to fully understand the behaviour. But yeah, iirc just pass all the *args up the chain
