### ISSUE TITLE
AttributeError: 'Tuple' object has no attribute 'id'

### ISSUE THREAD

**Issue by jaap3** [PyCQA/flake8-bugbear#9]
I'm able to consistently get an exception when running flake8-bugbear on this seemingly innocent code snippet (this has been reduced from code that actually did something):

```
def foo():
    for a, b in {}.items():
        pass
```

I'm using:

Python 3.5.2
flake8==3.2.1
flake8-bugbear==16.12.0

```
Traceback (most recent call last):
  ...
  File "bugbear.py", line 173, in visit_For
    if not node.target.id.startswith('_'):
AttributeError: 'Tuple' object has no attribute 'id'
```

**Comment by ambv** [comment]
Thanks for the report!

**Comment by advance512** [comment]
Great. I've just faced the same issue (I think):

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/user/proj/.venv/lib/python3.5/site-packages/flake8/checker.py", line 517, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 32, in run
    visitor.visit(self.tree)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 96, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 96, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 96, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 210, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 96, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 96, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/proj/.venv/lib/python3.5/site-packages/bugbear.py", line 173, in visit_For
    if not node.target.id.startswith('_'):
AttributeError: 'Tuple' object has no attribute 'id'
```

Please update when you push fix to PyPi.

**Comment by ambv** [comment]
16.12.1 just released.

**Comment by jaap3** [comment]
Thank you for the quick follow up and release!
